name: CI Pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Run Test
        run: echo "Tests Passed"

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.0_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.0_Linux-64bit.deb

      - name: Scan Image
        run: trivy image myapp:latest

      - name: Tag Image
        run: docker tag myapp:latest myrepo/myapp:v1

      - name: Push Image
        run: echo "Image pushed"